# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(317, 180)
        main_window.setMinimumSize(QtCore.QSize(50, 0))
        self.layoutWidget = QtWidgets.QWidget(main_window)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 301, 162))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_email = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_email.sizePolicy().hasHeightForWidth())
        self.label_email.setSizePolicy(sizePolicy)
        self.label_email.setMinimumSize(QtCore.QSize(60, 20))
        self.label_email.setMaximumSize(QtCore.QSize(60, 20))
        self.label_email.setObjectName("label_email")
        self.gridLayout.addWidget(self.label_email, 0, 0, 1, 1)
        self.lineEdit_email = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.gridLayout.addWidget(self.lineEdit_email, 0, 1, 1, 1)
        self.label_password = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_password.sizePolicy().hasHeightForWidth())
        self.label_password.setSizePolicy(sizePolicy)
        self.label_password.setMinimumSize(QtCore.QSize(60, 20))
        self.label_password.setMaximumSize(QtCore.QSize(60, 20))
        self.label_password.setObjectName("label_password")
        self.gridLayout.addWidget(self.label_password, 1, 0, 1, 1)
        self.lineEdit_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout.addWidget(self.lineEdit_password, 1, 1, 1, 1)
        self.pushButton_getCode = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_getCode.setObjectName("pushButton_getCode")
        self.gridLayout.addWidget(self.pushButton_getCode, 2, 0, 1, 2)
        self.label_time = QtWidgets.QLabel(self.layoutWidget)
        self.label_time.setMinimumSize(QtCore.QSize(60, 20))
        self.label_time.setMaximumSize(QtCore.QSize(60, 20))
        self.label_time.setObjectName("label_time")
        self.gridLayout.addWidget(self.label_time, 3, 0, 1, 1)
        self.label_time_value = QtWidgets.QLabel(self.layoutWidget)
        self.label_time_value.setText("")
        self.label_time_value.setObjectName("label_time_value")
        self.gridLayout.addWidget(self.label_time_value, 3, 1, 1, 1)
        self.label_code = QtWidgets.QLabel(self.layoutWidget)
        self.label_code.setMinimumSize(QtCore.QSize(60, 20))
        self.label_code.setMaximumSize(QtCore.QSize(60, 20))
        self.label_code.setObjectName("label_code")
        self.gridLayout.addWidget(self.label_code, 4, 0, 1, 1)
        self.lineEdit_code = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_code.setReadOnly(True)
        self.lineEdit_code.setObjectName("lineEdit_code")
        self.gridLayout.addWidget(self.lineEdit_code, 4, 1, 1, 1)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Steam code receiver"))
        self.label_email.setText(_translate("main_window", "Email"))
        self.label_password.setText(_translate("main_window", "Password"))
        self.pushButton_getCode.setText(_translate("main_window", "Get"))
        self.label_time.setText(_translate("main_window", "Received"))
        self.label_code.setText(_translate("main_window", "Code/URL"))
